<?xml version="1.0" encoding="utf-8"?>

<!-- Assignment 5 (Task 1) by ETHAN DAKIN (8209194) -->

<!DOCTYPE comparisons [
<!-- Element declarations -->
<!ELEMENT comparisons (hotel*)>
<!ELEMENT hotel (name, stars, reviews, score)>

<!-- Child elements, all are PCDATA -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT stars (#PCDATA)>
<!ELEMENT reviews (#PCDATA)>
<!ELEMENT score (#PCDATA)>

<!-- Attribute lists. -->
<!ATTLIST comparisons
          dated CDATA #REQUIRED
          location CDATA #REQUIRED
          company CDATA #REQUIRED
          url CDATA #REQUIRED>

]>

<!-- Comparisons element with attributes -->
<comparisons dated="2023-10-22" location="Sydney CBD" company="Trivago" url="https://www.trivago.com.au/">
  <!-- Hotel rows, with each value adjusted according to the assignment 5 specifications.  -->
  <hotel>
    <!-- All child elements for hotel element-->
    <name>Four Seasons Hotel Sydney</name>
    <stars>5</stars>
    <reviews>2641</reviews>
    <score>9.2</score>
  </hotel>

  <hotel>
    <name>Shangri-La Hotel Sydney</name>
    <stars>5</stars>
    <reviews>2990</reviews>
    <score>8.7</score>
  </hotel>

  <hotel>
    <name>Hilton Sydney</name>
    <stars>5</stars>
    <reviews>1772</reviews>
    <score>8.4</score>
  </hotel>

  <hotel>
    <name>Meriton Suites Kent Street</name>
    <stars>4</stars>
    <reviews>6611</reviews>
    <score>8.9</score>
  </hotel>

  <hotel>
    <name>Pier One Sydney Harbour (AC)</name>
    <stars>5</stars>
    <reviews>1572</reviews>
    <score>8.7</score>
  </hotel>

  <hotel>
    <name>West Hotel Sydney (CC)</name>
    <stars>4</stars>
    <reviews>1106</reviews>
    <score>9.2</score>
  </hotel>

  <hotel>
    <name>Hyatt Regency Sydney</name>
    <stars>5</stars>
    <reviews>1677</reviews>
    <score>8.3</score>
  </hotel>

  <hotel>
    <name>Oaks Sydney Goldsbrough Suites</name>
    <stars>4</stars>
    <reviews>1243</reviews>
    <score>7.6</score>
  </hotel>

  <hotel>
    <name>Park Hyatt Sydney</name>
    <stars>5</stars>
    <reviews>665</reviews>
    <score>9.2</score>
  </hotel>

  <hotel>
    <name>Meriton Suites World Tower</name>
    <stars>5</stars>
    <reviews>2901</reviews>
    <score>9.1</score>
  </hotel>
</comparisons>